a = input("enter string:\n")
print(a.upper())
print(a.lower())
print(len(a))
print(a.count("b", 0))
print(a.title())
print(a.istitle())
print(a.isupper())
print(a.islower())
print(a.swapcase())
print(a.find("b"))
print(a.rfind("a"))
print(a.replace("a", "d"))
print(a.index("a"))
print(a.rindex("b"))
print(a.strip())
print(a.rstrip())
print(a.lstrip())
print(a.split('b'))
print(a.isalpha())
print(a.isalnum())
print(a.isdecimal())
print(a.isdigit())
print(a.isnumeric())
